// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/objectauth/objectauth.proto
// DO NOT EDIT!

/*
Package objectauth is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/objectauth/objectauth.proto

It has these top-level messages:
	GroupToComposite
	UserToObject
	GroupToObject
	AuthRequest
	AuthResponse
	ObjectType
	ObjectIDList
	GrantUserRequest
	GrantGroupRequest
	PermissionSet
	AccessRightList
	ResolveResponse
	IDGrantRequest
	ResolveRequest
	AllAccessRequest
	AllAccessResponse
	GrantAllAccessRequest
	ServiceAccess
*/
package objectauth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"
import auth "golang.conradwood.net/apis/auth"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OBJECTTYPE int32

const (
	OBJECTTYPE_UNDEFINED        OBJECTTYPE = 0
	OBJECTTYPE_Service          OBJECTTYPE = 1
	OBJECTTYPE_Artefact         OBJECTTYPE = 2
	OBJECTTYPE_GitRepository    OBJECTTYPE = 3
	OBJECTTYPE_SingingCatModule OBJECTTYPE = 4
	OBJECTTYPE_Proto            OBJECTTYPE = 5
	OBJECTTYPE_Domain           OBJECTTYPE = 6
	OBJECTTYPE_UserAppFlags     OBJECTTYPE = 7
)

var OBJECTTYPE_name = map[int32]string{
	0: "UNDEFINED",
	1: "Service",
	2: "Artefact",
	3: "GitRepository",
	4: "SingingCatModule",
	5: "Proto",
	6: "Domain",
	7: "UserAppFlags",
}
var OBJECTTYPE_value = map[string]int32{
	"UNDEFINED":        0,
	"Service":          1,
	"Artefact":         2,
	"GitRepository":    3,
	"SingingCatModule": 4,
	"Proto":            5,
	"Domain":           6,
	"UserAppFlags":     7,
}

func (x OBJECTTYPE) String() string {
	return proto.EnumName(OBJECTTYPE_name, int32(x))
}
func (OBJECTTYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type COMPOSITETYPE int32

const (
	COMPOSITETYPE_COMP_UNDEFINED COMPOSITETYPE = 0
	COMPOSITETYPE_Software       COMPOSITETYPE = 1
)

var COMPOSITETYPE_name = map[int32]string{
	0: "COMP_UNDEFINED",
	1: "Software",
}
var COMPOSITETYPE_value = map[string]int32{
	"COMP_UNDEFINED": 0,
	"Software":       1,
}

func (x COMPOSITETYPE) String() string {
	return proto.EnumName(COMPOSITETYPE_name, int32(x))
}
func (COMPOSITETYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// composite types are some that include multiple, related objecttpyes, for example, a git repository and its artefacts and protos. in this case the ID is specific to _something_ in the composite relationships, in the example above, it is the "git repository id", from which the others are derived
type GroupToComposite struct {
	ID         uint64        `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	ObjectType COMPOSITETYPE `protobuf:"varint,2,opt,name=ObjectType,enum=objectauth.COMPOSITETYPE" json:"ObjectType,omitempty"`
	ObjectID   uint64        `protobuf:"varint,3,opt,name=ObjectID" json:"ObjectID,omitempty"`
	GroupID    string        `protobuf:"bytes,4,opt,name=GroupID" json:"GroupID,omitempty"`
	Active     bool          `protobuf:"varint,5,opt,name=Active" json:"Active,omitempty"`
	Read       bool          `protobuf:"varint,6,opt,name=Read" json:"Read,omitempty"`
	Write      bool          `protobuf:"varint,7,opt,name=Write" json:"Write,omitempty"`
	Execute    bool          `protobuf:"varint,8,opt,name=Execute" json:"Execute,omitempty"`
	View       bool          `protobuf:"varint,9,opt,name=View" json:"View,omitempty"`
}

func (m *GroupToComposite) Reset()                    { *m = GroupToComposite{} }
func (m *GroupToComposite) String() string            { return proto.CompactTextString(m) }
func (*GroupToComposite) ProtoMessage()               {}
func (*GroupToComposite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GroupToComposite) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GroupToComposite) GetObjectType() COMPOSITETYPE {
	if m != nil {
		return m.ObjectType
	}
	return COMPOSITETYPE_COMP_UNDEFINED
}

func (m *GroupToComposite) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *GroupToComposite) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *GroupToComposite) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *GroupToComposite) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *GroupToComposite) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *GroupToComposite) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *GroupToComposite) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

// database user to object acl
type UserToObject struct {
	ID         uint64     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	ObjectType OBJECTTYPE `protobuf:"varint,2,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ObjectID   uint64     `protobuf:"varint,3,opt,name=ObjectID" json:"ObjectID,omitempty"`
	UserID     string     `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
	Active     bool       `protobuf:"varint,5,opt,name=Active" json:"Active,omitempty"`
	Read       bool       `protobuf:"varint,6,opt,name=Read" json:"Read,omitempty"`
	Write      bool       `protobuf:"varint,7,opt,name=Write" json:"Write,omitempty"`
	Execute    bool       `protobuf:"varint,8,opt,name=Execute" json:"Execute,omitempty"`
	View       bool       `protobuf:"varint,9,opt,name=View" json:"View,omitempty"`
}

func (m *UserToObject) Reset()                    { *m = UserToObject{} }
func (m *UserToObject) String() string            { return proto.CompactTextString(m) }
func (*UserToObject) ProtoMessage()               {}
func (*UserToObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserToObject) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserToObject) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *UserToObject) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *UserToObject) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserToObject) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *UserToObject) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *UserToObject) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *UserToObject) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *UserToObject) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

// database group to object acl
type GroupToObject struct {
	ID         uint64     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	ObjectType OBJECTTYPE `protobuf:"varint,2,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ObjectID   uint64     `protobuf:"varint,3,opt,name=ObjectID" json:"ObjectID,omitempty"`
	GroupID    string     `protobuf:"bytes,4,opt,name=GroupID" json:"GroupID,omitempty"`
	Active     bool       `protobuf:"varint,5,opt,name=Active" json:"Active,omitempty"`
	Read       bool       `protobuf:"varint,6,opt,name=Read" json:"Read,omitempty"`
	Write      bool       `protobuf:"varint,7,opt,name=Write" json:"Write,omitempty"`
	Execute    bool       `protobuf:"varint,8,opt,name=Execute" json:"Execute,omitempty"`
	View       bool       `protobuf:"varint,9,opt,name=View" json:"View,omitempty"`
}

func (m *GroupToObject) Reset()                    { *m = GroupToObject{} }
func (m *GroupToObject) String() string            { return proto.CompactTextString(m) }
func (*GroupToObject) ProtoMessage()               {}
func (*GroupToObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GroupToObject) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GroupToObject) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *GroupToObject) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *GroupToObject) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *GroupToObject) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *GroupToObject) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *GroupToObject) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *GroupToObject) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *GroupToObject) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

//
// authenticate against objecttype and id. Using context to identify user
type AuthRequest struct {
	ObjectType     OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ObjectID       uint64     `protobuf:"varint,2,opt,name=ObjectID" json:"ObjectID,omitempty"`
	SubjectService string     `protobuf:"bytes,3,opt,name=SubjectService" json:"SubjectService,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthRequest) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *AuthRequest) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *AuthRequest) GetSubjectService() string {
	if m != nil {
		return m.SubjectService
	}
	return ""
}

type AuthResponse struct {
	Granted     bool           `protobuf:"varint,1,opt,name=Granted" json:"Granted,omitempty"`
	Permissions *PermissionSet `protobuf:"bytes,2,opt,name=Permissions" json:"Permissions,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthResponse) GetGranted() bool {
	if m != nil {
		return m.Granted
	}
	return false
}

func (m *AuthResponse) GetPermissions() *PermissionSet {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type ObjectType struct {
	ObjectType OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
}

func (m *ObjectType) Reset()                    { *m = ObjectType{} }
func (m *ObjectType) String() string            { return proto.CompactTextString(m) }
func (*ObjectType) ProtoMessage()               {}
func (*ObjectType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ObjectType) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

type ObjectIDList struct {
	ObjectIDs []uint64 `protobuf:"varint,1,rep,packed,name=ObjectIDs" json:"ObjectIDs,omitempty"`
}

func (m *ObjectIDList) Reset()                    { *m = ObjectIDList{} }
func (m *ObjectIDList) String() string            { return proto.CompactTextString(m) }
func (*ObjectIDList) ProtoMessage()               {}
func (*ObjectIDList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ObjectIDList) GetObjectIDs() []uint64 {
	if m != nil {
		return m.ObjectIDs
	}
	return nil
}

type GrantUserRequest struct {
	ObjectType OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ObjectID   uint64     `protobuf:"varint,2,opt,name=ObjectID" json:"ObjectID,omitempty"`
	UserID     string     `protobuf:"bytes,3,opt,name=UserID" json:"UserID,omitempty"`
	Read       bool       `protobuf:"varint,4,opt,name=Read" json:"Read,omitempty"`
	Write      bool       `protobuf:"varint,5,opt,name=Write" json:"Write,omitempty"`
	Execute    bool       `protobuf:"varint,6,opt,name=Execute" json:"Execute,omitempty"`
	View       bool       `protobuf:"varint,7,opt,name=View" json:"View,omitempty"`
}

func (m *GrantUserRequest) Reset()                    { *m = GrantUserRequest{} }
func (m *GrantUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GrantUserRequest) ProtoMessage()               {}
func (*GrantUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GrantUserRequest) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *GrantUserRequest) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *GrantUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GrantUserRequest) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *GrantUserRequest) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *GrantUserRequest) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *GrantUserRequest) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

type GrantGroupRequest struct {
	ObjectType OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ObjectID   uint64     `protobuf:"varint,2,opt,name=ObjectID" json:"ObjectID,omitempty"`
	GroupID    string     `protobuf:"bytes,3,opt,name=GroupID" json:"GroupID,omitempty"`
	Read       bool       `protobuf:"varint,4,opt,name=Read" json:"Read,omitempty"`
	Write      bool       `protobuf:"varint,5,opt,name=Write" json:"Write,omitempty"`
	Execute    bool       `protobuf:"varint,6,opt,name=Execute" json:"Execute,omitempty"`
	View       bool       `protobuf:"varint,7,opt,name=View" json:"View,omitempty"`
}

func (m *GrantGroupRequest) Reset()                    { *m = GrantGroupRequest{} }
func (m *GrantGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*GrantGroupRequest) ProtoMessage()               {}
func (*GrantGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GrantGroupRequest) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *GrantGroupRequest) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *GrantGroupRequest) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *GrantGroupRequest) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *GrantGroupRequest) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *GrantGroupRequest) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *GrantGroupRequest) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

type PermissionSet struct {
	Read    bool `protobuf:"varint,1,opt,name=Read" json:"Read,omitempty"`
	Write   bool `protobuf:"varint,2,opt,name=Write" json:"Write,omitempty"`
	Execute bool `protobuf:"varint,3,opt,name=Execute" json:"Execute,omitempty"`
	View    bool `protobuf:"varint,4,opt,name=View" json:"View,omitempty"`
}

func (m *PermissionSet) Reset()                    { *m = PermissionSet{} }
func (m *PermissionSet) String() string            { return proto.CompactTextString(m) }
func (*PermissionSet) ProtoMessage()               {}
func (*PermissionSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PermissionSet) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *PermissionSet) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *PermissionSet) GetExecute() bool {
	if m != nil {
		return m.Execute
	}
	return false
}

func (m *PermissionSet) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

type AccessRightList struct {
	ObjectType OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ObjectID   uint64     `protobuf:"varint,2,opt,name=ObjectID" json:"ObjectID,omitempty"`
	// GroupID to PermissionSet
	GroupPermissions map[string]*PermissionSet `protobuf:"bytes,3,rep,name=GroupPermissions" json:"GroupPermissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// UserID to Permission Set
	UserPermissions      map[string]*PermissionSet `protobuf:"bytes,4,rep,name=UserPermissions" json:"UserPermissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EffectivePermissions *PermissionSet            `protobuf:"bytes,5,opt,name=EffectivePermissions" json:"EffectivePermissions,omitempty"`
}

func (m *AccessRightList) Reset()                    { *m = AccessRightList{} }
func (m *AccessRightList) String() string            { return proto.CompactTextString(m) }
func (*AccessRightList) ProtoMessage()               {}
func (*AccessRightList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AccessRightList) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *AccessRightList) GetObjectID() uint64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *AccessRightList) GetGroupPermissions() map[string]*PermissionSet {
	if m != nil {
		return m.GroupPermissions
	}
	return nil
}

func (m *AccessRightList) GetUserPermissions() map[string]*PermissionSet {
	if m != nil {
		return m.UserPermissions
	}
	return nil
}

func (m *AccessRightList) GetEffectivePermissions() *PermissionSet {
	if m != nil {
		return m.EffectivePermissions
	}
	return nil
}

type ResolveResponse struct {
	AccessRightList *AccessRightList `protobuf:"bytes,1,opt,name=AccessRightList" json:"AccessRightList,omitempty"`
	User            *auth.User       `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
}

func (m *ResolveResponse) Reset()                    { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string            { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()               {}
func (*ResolveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResolveResponse) GetAccessRightList() *AccessRightList {
	if m != nil {
		return m.AccessRightList
	}
	return nil
}

func (m *ResolveResponse) GetUser() *auth.User {
	if m != nil {
		return m.User
	}
	return nil
}

type IDGrantRequest struct {
	ID      uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	GroupID string `protobuf:"bytes,2,opt,name=GroupID" json:"GroupID,omitempty"`
	UserID  string `protobuf:"bytes,3,opt,name=UserID" json:"UserID,omitempty"`
	Read    bool   `protobuf:"varint,4,opt,name=Read" json:"Read,omitempty"`
	Write   bool   `protobuf:"varint,5,opt,name=Write" json:"Write,omitempty"`
}

func (m *IDGrantRequest) Reset()                    { *m = IDGrantRequest{} }
func (m *IDGrantRequest) String() string            { return proto.CompactTextString(m) }
func (*IDGrantRequest) ProtoMessage()               {}
func (*IDGrantRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IDGrantRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *IDGrantRequest) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *IDGrantRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *IDGrantRequest) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *IDGrantRequest) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

type ResolveRequest struct {
	UserID      string       `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	AuthRequest *AuthRequest `protobuf:"bytes,2,opt,name=AuthRequest" json:"AuthRequest,omitempty"`
}

func (m *ResolveRequest) Reset()                    { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string            { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()               {}
func (*ResolveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ResolveRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ResolveRequest) GetAuthRequest() *AuthRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

// ask for access
type AllAccessRequest struct {
	ObjectType OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	ServiceID  string     `protobuf:"bytes,2,opt,name=ServiceID" json:"ServiceID,omitempty"`
}

func (m *AllAccessRequest) Reset()                    { *m = AllAccessRequest{} }
func (m *AllAccessRequest) String() string            { return proto.CompactTextString(m) }
func (*AllAccessRequest) ProtoMessage()               {}
func (*AllAccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AllAccessRequest) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *AllAccessRequest) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

// reply to "allaccess"
type AllAccessResponse struct {
	ReadAccess  bool `protobuf:"varint,1,opt,name=ReadAccess" json:"ReadAccess,omitempty"`
	WriteAccess bool `protobuf:"varint,2,opt,name=WriteAccess" json:"WriteAccess,omitempty"`
}

func (m *AllAccessResponse) Reset()                    { *m = AllAccessResponse{} }
func (m *AllAccessResponse) String() string            { return proto.CompactTextString(m) }
func (*AllAccessResponse) ProtoMessage()               {}
func (*AllAccessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AllAccessResponse) GetReadAccess() bool {
	if m != nil {
		return m.ReadAccess
	}
	return false
}

func (m *AllAccessResponse) GetWriteAccess() bool {
	if m != nil {
		return m.WriteAccess
	}
	return false
}

// grant "allaccess"
type GrantAllAccessRequest struct {
	ObjectType     OBJECTTYPE `protobuf:"varint,1,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
	CallingService string     `protobuf:"bytes,2,opt,name=CallingService" json:"CallingService,omitempty"`
	SubjectService string     `protobuf:"bytes,3,opt,name=SubjectService" json:"SubjectService,omitempty"`
	ReadAccess     bool       `protobuf:"varint,4,opt,name=ReadAccess" json:"ReadAccess,omitempty"`
	WriteAccess    bool       `protobuf:"varint,5,opt,name=WriteAccess" json:"WriteAccess,omitempty"`
}

func (m *GrantAllAccessRequest) Reset()                    { *m = GrantAllAccessRequest{} }
func (m *GrantAllAccessRequest) String() string            { return proto.CompactTextString(m) }
func (*GrantAllAccessRequest) ProtoMessage()               {}
func (*GrantAllAccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GrantAllAccessRequest) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func (m *GrantAllAccessRequest) GetCallingService() string {
	if m != nil {
		return m.CallingService
	}
	return ""
}

func (m *GrantAllAccessRequest) GetSubjectService() string {
	if m != nil {
		return m.SubjectService
	}
	return ""
}

func (m *GrantAllAccessRequest) GetReadAccess() bool {
	if m != nil {
		return m.ReadAccess
	}
	return false
}

func (m *GrantAllAccessRequest) GetWriteAccess() bool {
	if m != nil {
		return m.WriteAccess
	}
	return false
}

// database object to save "allaccess"
type ServiceAccess struct {
	ID             uint64     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	CallingService string     `protobuf:"bytes,2,opt,name=CallingService" json:"CallingService,omitempty"`
	SubjectService string     `protobuf:"bytes,3,opt,name=SubjectService" json:"SubjectService,omitempty"`
	CreatedBy      string     `protobuf:"bytes,4,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	Created        uint32     `protobuf:"varint,5,opt,name=Created" json:"Created,omitempty"`
	ReadAccess     bool       `protobuf:"varint,6,opt,name=ReadAccess" json:"ReadAccess,omitempty"`
	WriteAccess    bool       `protobuf:"varint,7,opt,name=WriteAccess" json:"WriteAccess,omitempty"`
	ObjectType     OBJECTTYPE `protobuf:"varint,8,opt,name=ObjectType,enum=objectauth.OBJECTTYPE" json:"ObjectType,omitempty"`
}

func (m *ServiceAccess) Reset()                    { *m = ServiceAccess{} }
func (m *ServiceAccess) String() string            { return proto.CompactTextString(m) }
func (*ServiceAccess) ProtoMessage()               {}
func (*ServiceAccess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ServiceAccess) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ServiceAccess) GetCallingService() string {
	if m != nil {
		return m.CallingService
	}
	return ""
}

func (m *ServiceAccess) GetSubjectService() string {
	if m != nil {
		return m.SubjectService
	}
	return ""
}

func (m *ServiceAccess) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ServiceAccess) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ServiceAccess) GetReadAccess() bool {
	if m != nil {
		return m.ReadAccess
	}
	return false
}

func (m *ServiceAccess) GetWriteAccess() bool {
	if m != nil {
		return m.WriteAccess
	}
	return false
}

func (m *ServiceAccess) GetObjectType() OBJECTTYPE {
	if m != nil {
		return m.ObjectType
	}
	return OBJECTTYPE_UNDEFINED
}

func init() {
	proto.RegisterType((*GroupToComposite)(nil), "objectauth.GroupToComposite")
	proto.RegisterType((*UserToObject)(nil), "objectauth.UserToObject")
	proto.RegisterType((*GroupToObject)(nil), "objectauth.GroupToObject")
	proto.RegisterType((*AuthRequest)(nil), "objectauth.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "objectauth.AuthResponse")
	proto.RegisterType((*ObjectType)(nil), "objectauth.ObjectType")
	proto.RegisterType((*ObjectIDList)(nil), "objectauth.ObjectIDList")
	proto.RegisterType((*GrantUserRequest)(nil), "objectauth.GrantUserRequest")
	proto.RegisterType((*GrantGroupRequest)(nil), "objectauth.GrantGroupRequest")
	proto.RegisterType((*PermissionSet)(nil), "objectauth.PermissionSet")
	proto.RegisterType((*AccessRightList)(nil), "objectauth.AccessRightList")
	proto.RegisterType((*ResolveResponse)(nil), "objectauth.ResolveResponse")
	proto.RegisterType((*IDGrantRequest)(nil), "objectauth.IDGrantRequest")
	proto.RegisterType((*ResolveRequest)(nil), "objectauth.ResolveRequest")
	proto.RegisterType((*AllAccessRequest)(nil), "objectauth.AllAccessRequest")
	proto.RegisterType((*AllAccessResponse)(nil), "objectauth.AllAccessResponse")
	proto.RegisterType((*GrantAllAccessRequest)(nil), "objectauth.GrantAllAccessRequest")
	proto.RegisterType((*ServiceAccess)(nil), "objectauth.ServiceAccess")
	proto.RegisterEnum("objectauth.OBJECTTYPE", OBJECTTYPE_name, OBJECTTYPE_value)
	proto.RegisterEnum("objectauth.COMPOSITETYPE", COMPOSITETYPE_name, COMPOSITETYPE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ObjectAuthService service

type ObjectAuthServiceClient interface {
	//
	// check if a given service has got access to all such objects in a given service
	// for example: "Does h2gproxy have access to all users? -> no"
	// for example: "Does htmlserver (if called by h2gproxy) have access to all users? -> yes"
	AllowAllServiceAccess(ctx context.Context, in *AllAccessRequest, opts ...grpc.CallOption) (*AllAccessResponse, error)
	// allow a service to access all objects
	GrantAllServiceAccess(ctx context.Context, in *GrantAllAccessRequest, opts ...grpc.CallOption) (*common.Void, error)
	// ask if calling user or a given service has access to an object. accessrights of service and user merged to form the most permissive set of accessrights
	AskObjectAccess(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// get all objects (of a given type) the current user has access to
	AvailableObjects(ctx context.Context, in *ObjectType, opts ...grpc.CallOption) (*ObjectIDList, error)
	// grant access to a user. Currently this call is privileged for root users only
	GrantToUser(ctx context.Context, in *GrantUserRequest, opts ...grpc.CallOption) (*common.Void, error)
	// grant access to a group. Currently this call is privileged for root users only
	GrantToGroup(ctx context.Context, in *GrantGroupRequest, opts ...grpc.CallOption) (*common.Void, error)
	// grant access to me. Currently this call is privileged for root users only. Leave the userid field to 0
	GrantToMe(ctx context.Context, in *GrantUserRequest, opts ...grpc.CallOption) (*common.Void, error)
	// get acessrights for calling user for a specific object
	GetRights(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AccessRightList, error)
	// give access to a sourcecode repository, its proto and its artefact
	GrantToSoftware(ctx context.Context, in *IDGrantRequest, opts ...grpc.CallOption) (*common.Void, error)
	// privileged for admins - get permissions for a particular user (to check permissions)
	ResolveForUser(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type objectAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewObjectAuthServiceClient(cc *grpc.ClientConn) ObjectAuthServiceClient {
	return &objectAuthServiceClient{cc}
}

func (c *objectAuthServiceClient) AllowAllServiceAccess(ctx context.Context, in *AllAccessRequest, opts ...grpc.CallOption) (*AllAccessResponse, error) {
	out := new(AllAccessResponse)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/AllowAllServiceAccess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) GrantAllServiceAccess(ctx context.Context, in *GrantAllAccessRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/GrantAllServiceAccess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) AskObjectAccess(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/AskObjectAccess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) AvailableObjects(ctx context.Context, in *ObjectType, opts ...grpc.CallOption) (*ObjectIDList, error) {
	out := new(ObjectIDList)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/AvailableObjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) GrantToUser(ctx context.Context, in *GrantUserRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/GrantToUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) GrantToGroup(ctx context.Context, in *GrantGroupRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/GrantToGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) GrantToMe(ctx context.Context, in *GrantUserRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/GrantToMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) GetRights(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AccessRightList, error) {
	out := new(AccessRightList)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/GetRights", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) GrantToSoftware(ctx context.Context, in *IDGrantRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/GrantToSoftware", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAuthServiceClient) ResolveForUser(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := grpc.Invoke(ctx, "/objectauth.ObjectAuthService/ResolveForUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ObjectAuthService service

type ObjectAuthServiceServer interface {
	//
	// check if a given service has got access to all such objects in a given service
	// for example: "Does h2gproxy have access to all users? -> no"
	// for example: "Does htmlserver (if called by h2gproxy) have access to all users? -> yes"
	AllowAllServiceAccess(context.Context, *AllAccessRequest) (*AllAccessResponse, error)
	// allow a service to access all objects
	GrantAllServiceAccess(context.Context, *GrantAllAccessRequest) (*common.Void, error)
	// ask if calling user or a given service has access to an object. accessrights of service and user merged to form the most permissive set of accessrights
	AskObjectAccess(context.Context, *AuthRequest) (*AuthResponse, error)
	// get all objects (of a given type) the current user has access to
	AvailableObjects(context.Context, *ObjectType) (*ObjectIDList, error)
	// grant access to a user. Currently this call is privileged for root users only
	GrantToUser(context.Context, *GrantUserRequest) (*common.Void, error)
	// grant access to a group. Currently this call is privileged for root users only
	GrantToGroup(context.Context, *GrantGroupRequest) (*common.Void, error)
	// grant access to me. Currently this call is privileged for root users only. Leave the userid field to 0
	GrantToMe(context.Context, *GrantUserRequest) (*common.Void, error)
	// get acessrights for calling user for a specific object
	GetRights(context.Context, *AuthRequest) (*AccessRightList, error)
	// give access to a sourcecode repository, its proto and its artefact
	GrantToSoftware(context.Context, *IDGrantRequest) (*common.Void, error)
	// privileged for admins - get permissions for a particular user (to check permissions)
	ResolveForUser(context.Context, *ResolveRequest) (*ResolveResponse, error)
}

func RegisterObjectAuthServiceServer(s *grpc.Server, srv ObjectAuthServiceServer) {
	s.RegisterService(&_ObjectAuthService_serviceDesc, srv)
}

func _ObjectAuthService_AllowAllServiceAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).AllowAllServiceAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/AllowAllServiceAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).AllowAllServiceAccess(ctx, req.(*AllAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_GrantAllServiceAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAllAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).GrantAllServiceAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/GrantAllServiceAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).GrantAllServiceAccess(ctx, req.(*GrantAllAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_AskObjectAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).AskObjectAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/AskObjectAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).AskObjectAccess(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_AvailableObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).AvailableObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/AvailableObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).AvailableObjects(ctx, req.(*ObjectType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_GrantToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).GrantToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/GrantToUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).GrantToUser(ctx, req.(*GrantUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_GrantToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).GrantToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/GrantToGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).GrantToGroup(ctx, req.(*GrantGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_GrantToMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).GrantToMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/GrantToMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).GrantToMe(ctx, req.(*GrantUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_GetRights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).GetRights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/GetRights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).GetRights(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_GrantToSoftware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).GrantToSoftware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/GrantToSoftware",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).GrantToSoftware(ctx, req.(*IDGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAuthService_ResolveForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAuthServiceServer).ResolveForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectauth.ObjectAuthService/ResolveForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAuthServiceServer).ResolveForUser(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ObjectAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "objectauth.ObjectAuthService",
	HandlerType: (*ObjectAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllowAllServiceAccess",
			Handler:    _ObjectAuthService_AllowAllServiceAccess_Handler,
		},
		{
			MethodName: "GrantAllServiceAccess",
			Handler:    _ObjectAuthService_GrantAllServiceAccess_Handler,
		},
		{
			MethodName: "AskObjectAccess",
			Handler:    _ObjectAuthService_AskObjectAccess_Handler,
		},
		{
			MethodName: "AvailableObjects",
			Handler:    _ObjectAuthService_AvailableObjects_Handler,
		},
		{
			MethodName: "GrantToUser",
			Handler:    _ObjectAuthService_GrantToUser_Handler,
		},
		{
			MethodName: "GrantToGroup",
			Handler:    _ObjectAuthService_GrantToGroup_Handler,
		},
		{
			MethodName: "GrantToMe",
			Handler:    _ObjectAuthService_GrantToMe_Handler,
		},
		{
			MethodName: "GetRights",
			Handler:    _ObjectAuthService_GetRights_Handler,
		},
		{
			MethodName: "GrantToSoftware",
			Handler:    _ObjectAuthService_GrantToSoftware_Handler,
		},
		{
			MethodName: "ResolveForUser",
			Handler:    _ObjectAuthService_ResolveForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/golang.conradwood.net/apis/objectauth/objectauth.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/objectauth/objectauth.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x58, 0x6d, 0x6f, 0xe3, 0xc4,
	0x13, 0xff, 0x3b, 0xcf, 0x9e, 0x3c, 0xd4, 0x5d, 0xf5, 0xee, 0xef, 0x0b, 0xbd, 0x53, 0xb0, 0x74,
	0xa7, 0xe8, 0x84, 0x52, 0xae, 0xa0, 0x83, 0x52, 0xf1, 0xc2, 0x8d, 0xd3, 0x12, 0x44, 0x1f, 0xe4,
	0xa4, 0x87, 0x38, 0xe9, 0x40, 0x6e, 0xb2, 0x4d, 0xcd, 0xb9, 0xde, 0x60, 0x6f, 0xda, 0xab, 0xc4,
	0x2b, 0x78, 0x03, 0x5f, 0x81, 0xef, 0x00, 0x5f, 0x80, 0xef, 0x81, 0xc4, 0x4b, 0xbe, 0x06, 0x12,
	0x12, 0xf2, 0x7a, 0x1d, 0xaf, 0x9d, 0x34, 0xbd, 0x87, 0xf6, 0xc4, 0xab, 0x64, 0xc6, 0x3b, 0xbf,
	0x99, 0xdf, 0xec, 0xcc, 0x8e, 0xd7, 0xf0, 0xe9, 0xd8, 0x23, 0x94, 0xf8, 0x6b, 0x23, 0xe2, 0x58,
	0xee, 0xa8, 0x35, 0x20, 0xae, 0x67, 0x0d, 0xcf, 0x09, 0x19, 0xb6, 0x5c, 0x4c, 0xd7, 0xac, 0xb1,
	0xed, 0xaf, 0x91, 0xa3, 0x6f, 0xf1, 0x80, 0x5a, 0x13, 0x7a, 0x22, 0xfc, 0x6d, 0x31, 0x3b, 0x04,
	0xb1, 0xa6, 0xde, 0x5a, 0x80, 0x31, 0x20, 0xa7, 0xa7, 0xc4, 0xe5, 0x3f, 0xa1, 0x6d, 0xfd, 0xe1,
	0x82, 0xf5, 0xcc, 0x5b, 0xec, 0x47, 0xfb, 0x31, 0x03, 0xca, 0x8e, 0x47, 0x26, 0xe3, 0x3e, 0x69,
	0x93, 0xd3, 0x31, 0xf1, 0x6d, 0x8a, 0x51, 0x0d, 0x32, 0x5d, 0x43, 0x95, 0x1a, 0x52, 0x33, 0x67,
	0x66, 0xba, 0x06, 0xda, 0x00, 0xd8, 0x67, 0xe1, 0xf4, 0x2f, 0xc6, 0x58, 0xcd, 0x34, 0xa4, 0x66,
	0x6d, 0xfd, 0x4e, 0x4b, 0x88, 0xb9, 0xbd, 0xbf, 0x7b, 0xb0, 0xdf, 0xeb, 0xf6, 0x3b, 0xfd, 0xaf,
	0x0e, 0x3a, 0xa6, 0xb0, 0x18, 0xd5, 0xa1, 0x14, 0x4a, 0x5d, 0x43, 0xcd, 0x32, 0xc0, 0xa9, 0x8c,
	0x54, 0x28, 0x32, 0xd7, 0x5d, 0x43, 0xcd, 0x35, 0xa4, 0xa6, 0x6c, 0x46, 0x22, 0xba, 0x0d, 0x05,
	0x7d, 0x40, 0xed, 0x33, 0xac, 0xe6, 0x1b, 0x52, 0xb3, 0x64, 0x72, 0x09, 0x21, 0xc8, 0x99, 0xd8,
	0x1a, 0xaa, 0x05, 0xa6, 0x65, 0xff, 0xd1, 0x0a, 0xe4, 0xbf, 0xf4, 0x6c, 0x8a, 0xd5, 0x22, 0x53,
	0x86, 0x42, 0x80, 0xdd, 0x79, 0x81, 0x07, 0x13, 0x8a, 0xd5, 0x12, 0xd3, 0x47, 0x62, 0x80, 0xf1,
	0xc4, 0xc6, 0xe7, 0xaa, 0x1c, 0x62, 0x04, 0xff, 0xb5, 0xbf, 0x25, 0xa8, 0x1c, 0xfa, 0xd8, 0xeb,
	0x93, 0x30, 0xb8, 0x99, 0x0c, 0x3c, 0x9e, 0x93, 0x81, 0xdb, 0x62, 0x06, 0xf6, 0xb7, 0x3e, 0xef,
	0xb4, 0xfb, 0xaf, 0x44, 0xff, 0x36, 0x14, 0x02, 0x9f, 0x53, 0xf6, 0x5c, 0x7a, 0xeb, 0xe4, 0xff,
	0x91, 0xa0, 0xca, 0x4b, 0xe0, 0x2d, 0xb2, 0xff, 0xef, 0x6c, 0xfe, 0xcf, 0x12, 0x94, 0xf5, 0x09,
	0x3d, 0x31, 0xf1, 0x77, 0x13, 0xec, 0xd3, 0x14, 0x5b, 0xe9, 0xb5, 0xd8, 0x66, 0x52, 0x6c, 0x1f,
	0x40, 0xad, 0x37, 0x61, 0x42, 0x0f, 0x7b, 0x67, 0xf6, 0x00, 0xb3, 0x7c, 0xc8, 0x66, 0x4a, 0xab,
	0x61, 0xa8, 0x84, 0xa1, 0xf8, 0x63, 0xe2, 0xfa, 0x38, 0xcc, 0x92, 0xe5, 0x52, 0x3c, 0x64, 0x81,
	0x94, 0xcc, 0x48, 0x44, 0x9b, 0x50, 0x3e, 0xc0, 0xde, 0xa9, 0xed, 0xfb, 0x36, 0x71, 0x7d, 0xe6,
	0xb0, 0x9c, 0x6c, 0xca, 0xf8, 0x71, 0x0f, 0x53, 0x53, 0x5c, 0xad, 0x19, 0x22, 0xc5, 0xd7, 0x25,
	0xac, 0xbd, 0x07, 0x95, 0x88, 0xe0, 0x17, 0xb6, 0x4f, 0xd1, 0x2a, 0xc8, 0x91, 0xec, 0xab, 0x52,
	0x23, 0xdb, 0xcc, 0x99, 0xb1, 0x42, 0xfb, 0x43, 0x0a, 0x4e, 0x1a, 0xcb, 0xa5, 0x41, 0x99, 0xdf,
	0x64, 0xae, 0xe3, 0xbe, 0xca, 0x26, 0xfa, 0x2a, 0xaa, 0x9f, 0xdc, 0xbc, 0xfa, 0xc9, 0x5f, 0x52,
	0x3f, 0x85, 0xf9, 0xf5, 0x53, 0x14, 0xea, 0xe7, 0x4f, 0x09, 0x96, 0x19, 0x31, 0x56, 0xc0, 0x37,
	0xc9, 0x4c, 0xe8, 0x99, 0x6c, 0xb2, 0x67, 0x6e, 0x8a, 0xdb, 0x08, 0xaa, 0x89, 0x32, 0x9a, 0x3a,
	0x92, 0xe6, 0x39, 0xca, 0x5c, 0xe2, 0x28, 0x3b, 0xdf, 0x51, 0x4e, 0x70, 0xf4, 0x5b, 0x0e, 0x96,
	0xf4, 0xc1, 0x00, 0xfb, 0xbe, 0x69, 0x8f, 0x4e, 0x28, 0xab, 0xa7, 0x9b, 0x48, 0xe1, 0x33, 0x3e,
	0xee, 0xc4, 0xde, 0xc9, 0x36, 0xb2, 0xcd, 0xf2, 0xfa, 0x23, 0x11, 0x39, 0x15, 0x4a, 0x2b, 0x6d,
	0xd3, 0x71, 0xa9, 0x77, 0x61, 0xce, 0x40, 0xa1, 0xa7, 0xb0, 0x14, 0x54, 0x9b, 0x88, 0x9e, 0x63,
	0xe8, 0xef, 0x2f, 0x42, 0x4f, 0x99, 0x84, 0xe0, 0x69, 0x20, 0xb4, 0x0b, 0x2b, 0x9d, 0xe3, 0x63,
	0xcc, 0x0e, 0x43, 0xd1, 0x41, 0xfe, 0xaa, 0xd6, 0x9f, 0x6b, 0x56, 0xff, 0x1a, 0x6e, 0xcd, 0x65,
	0x85, 0x14, 0xc8, 0x3e, 0xc7, 0x17, 0x2c, 0xdf, 0xb2, 0x19, 0xfc, 0x45, 0x6b, 0x90, 0x3f, 0xb3,
	0x9c, 0x09, 0xbe, 0xfa, 0x94, 0x09, 0xd7, 0x7d, 0x92, 0xf9, 0x58, 0xaa, 0x3f, 0x83, 0x95, 0x79,
	0xbc, 0xae, 0x09, 0x5e, 0x7b, 0x01, 0x4b, 0x26, 0xf6, 0x89, 0x73, 0x86, 0xa7, 0x87, 0x65, 0x67,
	0xa6, 0x84, 0x98, 0x97, 0xf2, 0xfa, 0x3b, 0x0b, 0x92, 0x6f, 0xce, 0x94, 0xdd, 0x3d, 0xc8, 0x05,
	0x81, 0xf3, 0x68, 0xa0, 0xc5, 0xac, 0xd8, 0xa1, 0xc5, 0xf4, 0xda, 0xf7, 0x50, 0xeb, 0x1a, 0xac,
	0xe1, 0xa3, 0x5e, 0x4f, 0xcf, 0x4b, 0xa1, 0x4f, 0x33, 0x33, 0xb3, 0xed, 0xcd, 0xce, 0x26, 0x6d,
	0x00, 0xb5, 0x29, 0xef, 0xd0, 0x7b, 0x8c, 0x29, 0x25, 0x30, 0x37, 0x12, 0x63, 0x8d, 0xd3, 0xf9,
	0x7f, 0x22, 0x15, 0xf1, 0x63, 0x53, 0x5c, 0xab, 0x9d, 0x80, 0xa2, 0x3b, 0x0e, 0x4f, 0xcc, 0x1b,
	0x1e, 0x68, 0xab, 0x20, 0xf3, 0xe9, 0x36, 0x4d, 0x47, 0xac, 0xd0, 0x0e, 0x61, 0x59, 0xf0, 0xc4,
	0x37, 0xf2, 0x1e, 0x40, 0x90, 0x81, 0x50, 0xcb, 0x8f, 0x1a, 0x41, 0x83, 0x1a, 0x50, 0x66, 0xc9,
	0xe0, 0x0b, 0xc2, 0x63, 0x47, 0x54, 0x69, 0x7f, 0x49, 0x41, 0x75, 0x5b, 0x2e, 0xbd, 0x36, 0x1a,
	0x0f, 0xa0, 0xd6, 0xb6, 0x1c, 0xc7, 0x76, 0x47, 0xd1, 0x04, 0x0f, 0xb9, 0xa4, 0xb4, 0x2f, 0x3b,
	0xe9, 0x53, 0x1c, 0x73, 0x57, 0x71, 0xcc, 0xcf, 0x72, 0xfc, 0x35, 0x03, 0x55, 0x8e, 0xc6, 0x6d,
	0xd2, 0x75, 0x78, 0xdd, 0x31, 0xaf, 0x82, 0xdc, 0xf6, 0xb0, 0x45, 0xf1, 0x70, 0xeb, 0x82, 0xbf,
	0xb5, 0xc5, 0x8a, 0xa0, 0xea, 0xb9, 0xc0, 0xa2, 0xad, 0x9a, 0x91, 0x98, 0xe2, 0x5a, 0xb8, 0x8a,
	0x6b, 0x71, 0x86, 0x2b, 0xda, 0x4a, 0xec, 0x5a, 0x69, 0xd1, 0xae, 0x6d, 0xc1, 0x2f, 0x3f, 0xdc,
	0x29, 0x4c, 0x6c, 0x97, 0x3e, 0xfe, 0x50, 0xdc, 0xc1, 0x87, 0x3f, 0x49, 0x00, 0xf1, 0x32, 0x54,
	0x05, 0xf9, 0x70, 0xcf, 0xe8, 0x6c, 0x77, 0xf7, 0x3a, 0x86, 0xf2, 0x3f, 0x54, 0x86, 0x22, 0xa7,
	0xa9, 0x48, 0xa8, 0x02, 0x25, 0xdd, 0xa3, 0xf8, 0xd8, 0x1a, 0x50, 0x25, 0x83, 0x96, 0xa1, 0xba,
	0x63, 0x53, 0x13, 0xb3, 0xdb, 0x11, 0xf1, 0x2e, 0x94, 0x2c, 0x5a, 0x01, 0xa5, 0x67, 0xbb, 0x23,
	0xdb, 0x1d, 0xb5, 0x2d, 0xba, 0x4b, 0x86, 0x13, 0x07, 0x2b, 0x39, 0x24, 0x43, 0xfe, 0x20, 0xb8,
	0x55, 0x29, 0x79, 0x04, 0x50, 0x30, 0xc8, 0xa9, 0x65, 0xbb, 0x4a, 0x01, 0x29, 0xe1, 0xe5, 0x42,
	0x1f, 0x8f, 0xb7, 0x1d, 0x6b, 0xe4, 0x2b, 0xc5, 0x87, 0x8f, 0xa0, 0x9a, 0xb8, 0x32, 0x21, 0x04,
	0xb5, 0x40, 0xf1, 0x8d, 0x18, 0x51, 0x05, 0x4a, 0x3d, 0x72, 0x4c, 0xcf, 0x2d, 0x0f, 0x2b, 0xd2,
	0xfa, 0xef, 0x79, 0x58, 0x0e, 0xc9, 0x04, 0x8d, 0x1a, 0xed, 0x48, 0x1f, 0x6e, 0xe9, 0x8e, 0x43,
	0xce, 0x75, 0xc7, 0x49, 0x96, 0xc2, 0x6a, 0xa2, 0xcf, 0x53, 0x4d, 0x50, 0xbf, 0x7b, 0xc9, 0x53,
	0xde, 0x7f, 0x9f, 0xc5, 0xcd, 0x93, 0x44, 0x7d, 0x57, 0xb4, 0x9b, 0xdb, 0x5f, 0xf5, 0x4a, 0x8b,
	0xdf, 0x45, 0x9f, 0x10, 0x7b, 0x88, 0x0c, 0x58, 0xd2, 0xfd, 0xe7, 0x3c, 0xee, 0x10, 0xe3, 0xb2,
	0x13, 0xa8, 0xae, 0xce, 0x3e, 0xe0, 0xf1, 0x18, 0xa0, 0xe8, 0x67, 0x96, 0xed, 0x58, 0x47, 0x0e,
	0x0e, 0xb1, 0x7c, 0x94, 0xdc, 0xfd, 0xe9, 0x2e, 0x27, 0x51, 0x12, 0xaf, 0xa7, 0x1b, 0x50, 0x66,
	0x21, 0xf7, 0x49, 0xb0, 0x1b, 0xc9, 0x0c, 0xa5, 0x5f, 0x4c, 0x53, 0x34, 0x36, 0xa1, 0xc2, 0x4d,
	0xd9, 0x41, 0x8e, 0xee, 0xce, 0xd8, 0x8a, 0xef, 0x7e, 0x29, 0xe3, 0x8f, 0x40, 0xe6, 0xc6, 0xbb,
	0xf8, 0x95, 0xbc, 0xea, 0x20, 0xef, 0x60, 0xca, 0x06, 0xd3, 0x82, 0xb4, 0x2d, 0x1a, 0x6e, 0x68,
	0x13, 0x96, 0xb8, 0xef, 0xa8, 0x94, 0x50, 0x5d, 0x5c, 0x9f, 0x1c, 0x64, 0x29, 0xff, 0xdd, 0xe9,
	0xa8, 0xd9, 0x26, 0x1e, 0xcb, 0x59, 0xc2, 0x36, 0x39, 0x86, 0x92, 0x71, 0xa4, 0x46, 0xf3, 0xd6,
	0x1e, 0xdc, 0x77, 0x31, 0x15, 0xbf, 0x48, 0xf0, 0x6f, 0x14, 0xd6, 0xd8, 0xf6, 0x05, 0xc3, 0xa7,
	0xf7, 0x5f, 0xea, 0x7b, 0xc9, 0x51, 0x81, 0x7d, 0xbd, 0xf8, 0xe0, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x71, 0xcb, 0xa0, 0x8f, 0x66, 0x11, 0x00, 0x00,
}



